In [2]:
from sklearn.mixture import GaussianMixture
import numpy as np
# Dataset
X = np.array([[1,2],[1,4],[1,0],
[10,2],[10,4],[10,0]])
# Create model
gmm = GaussianMixture(n_components=2) # Train model
gmm.fit(X) # Prediction
labels = gmm.predict(X)
print("Cluster Labels:")
print(labels)

# EXPECTATION MAXIMIZATION
from scipy.stats import multivariate_normal

# Generate Sample Data
np.random.seed(0)
# Two clusters
data1 = np.random.normal(2, 0.5, (100, 1))
data2 = np.random.normal(8, 0.5, (100, 1))
X = np.vstack((data1, data2))

# Initialize Parameters
k = 2  # number of clusters
n = X.shape[0]
# Initial means
means = np.random.choice(X.flatten(), k).reshape(k, 1)
# Initial variances
variances = np.ones((k, 1))
# Mixing coefficients
weights = np.ones(k) / k

# EM Algorithm
iterations = 10
for iteration in range(iterations):
    # E-step: Calculate responsibilities
    responsibilities = np.zeros((n, k))
    for i in range(k):
        dist = multivariate_normal(mean=means[i].flatten(),
                                   cov=variances[i])
        responsibilities[:, i] = weights[i] * dist.pdf(X.flatten())
    # Normalize responsibilities
    responsibilities /= responsibilities.sum(axis=1, keepdims=True)
    # M-step: Update parameters
    Nk = responsibilities.sum(axis=0)
    for i in range(k):
        means[i] = (responsibilities[:, i] @ X) / Nk[i]
        variances[i] = ((responsibilities[:, i] * (X.flatten() - means[i])**2).sum()) / Nk[i]
        weights[i] = Nk[i] / n

# Output Results
print("Final Means:\n", means)
print("Final Variances:\n", variances)
print("Mixing Coefficients:\n", weights)

Cluster Labels:
[1 1 1 0 0 0]
Final Means:
 [[2.02990401]
 [8.04100649]]
Final Variances:
 [[0.25395665]
 [0.26763395]]
Mixing Coefficients:
 [0.5 0.5]
